# Generated by Django 5.1.6 on 2025-03-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_watch_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
