const videoArray=[
    require("./videos/Counter-Strike 2 - Official Launch Trailer.mp4"),
    require("./videos/Cyberpunk 2077 — Official E3 2018 Trailer.mp4"),
    require("./videos/Multiplayer Trailer _ Call of Duty_ Modern Warfare III.mp4"),
    require("./videos/Grand Theft Auto V_ The Official Trailer.mp4"),
    require("./videos/HITMAN 3 - Announcement Trailer.mp4"),
    require("./videos/The Witcher 3 Wild Hunt Next Gen Update Official Trailer.mp4"),
    require("./videos/The Last of Us Launch Trailer - E3 2013.mp4"),
    require("./videos/World of Warships_ Legends - Official Trailer.mp4"),
    require("./videos/RoboCop_ Rogue City - Official Trailer.mp4"),
    require("./videos/Call to Arms - Gates of Hell_ Liberation Trailer.mp4"),
    require("./videos/Star Wars Jedi_ Survivor - Official Story Trailer.mp4"),
    require("./videos/Days Gone – Features Trailer _ PC.mp4"),
    require("./videos/Starfield_ Official Teaser Trailer.mp4"),
    require("./videos/New World_ Aeternum Awaits - Official Trailer.mp4"),
    require("./videos/Sons of the Forest - Exclusive Multiplayer Trailer.mp4"),
    require("./videos/The Elder Scrolls V_ Skyrim - Official Trailer.mp4"),
    require("./videos/Metal Gear Solid V_ The Phantom Pain - GAMEPLAY TRAILER.mp4"),
    require("./videos/Hellblade_ Senua's Sacrifice - Official Enhanced for PC Trailer.mp4"),
    require("./videos/Sengoku Dynasty - Official Cinematic Trailer.mp4"),
    require("./videos/GOD OF WAR 4 Cinematic Trailer (2018).mp4"),
    require("./videos/The Sims 4_ Newcrest Official Trailer.mp4"),
    require("./videos/Apocalypse Party _ Launch Trailer.mp4"),
    require("./videos/Cities_Skyline.mp4"),
    require("./videos/Kayak VR_ Mirage Launch Trailer.mp4"),
    require("./videos/Lords Mobile - Cinematic Trailer (Puppetworks Animation Studio).mp4"),
    require("./videos/Hearts of Iron IV_ Arms Against Tyranny _ Official Announcement Trailer.mp4"),
    require("./videos/Plants vs. Zombies Game Trailer.mp4"),
    require("./videos/Megaquarium - Gameplay Trailer _ PS4.mp4"),
    require("./videos/Total War_ THREE KINGDOMS - Dong Zhuo Reveal Trailer.mp4"),
    require("./videos/WWE 2K23 - Official Gameplay Trailer.mp4"),
    require("./videos/Destiny 2_ The Final Shape _ Teaser Trailer.mp4"),
    require("./videos/Lost Ark Trailer _ Summer Game Fest 2021.mp4"),
    require("./videos/WarThunder.mp4"),
    require("./videos/Warframe.mp4"),
    require("./videos/The Elder Scrolls Online_ Firesong Gameplay Trailer.mp4"),
    require("./videos/ARK_ Survival Evolved - Launch Trailer _ PS4.mp4"),
    require("./videos/The Front - Official Early Access Release Date Trailer.mp4"),
    require("./videos/The CGI trailer for Game of Thrones Winter is Coming.mp4"),
    require("./videos/V Rising - Gameplay Trailer.mp4"),
    require("./videos/Battlefield V - Official Launch Trailer.mp4"),
    require("./videos/Forza Horizon 5 - Official Launch Trailer.mp4"),
    require("./videos/SnowRunner - Launch Trailer.mp4"),
    require("./videos/iRacing - Race With Us.mp4"),
    require("./videos/CarX Drift Racing Online Release Trailer [Steam].mp4"),
    require("./videos/Car Mechanic Simulator 2018 - Official Gameplay Trailer.mp4"),
    require("./videos/DiRT Rally 2.0 _ The Announcement Trailer _ PS4.mp4"),
    require("./videos/RealFlight Evolution RC Flight Simulator.mp4"),
    require("./videos/Wreckfest - Console Release Trailer _ PS4.mp4"),
    require("./videos/Need for Speed Unbound - Official Reveal Trailer (ft. A$AP Rocky).mp4"),
    require("./videos/F1® Manager 23 _ Official Launch Trailer.mp4"),
    require("./videos/EA SPORTS FC 24 _ Official Announce Trailer.mp4"),
    require("./videos/NBA 2K24 - Official Season 3 Trailer.mp4"),
    require("./videos/eFootball 2024 Official Launch Trailer.mp4"),
    require("./videos/Madden 24 Official Reveal Trailer.mp4"),
    require("./videos/F1® 23 _ Official Reveal Trailer.mp4"),
    require("./videos/rFactor 2 - Trailer.mp4"),
    require("./videos/Assetto Corsa Competizione - Official Trailer V1.1.mp4"),
    require("./videos/PGA Tour 2K23 - Official Announce Trailer.mp4"),
    require("./videos/theHunter_ Call of the Wild  _  Announcement Trailer.mp4"),
    require("./videos/movie_max_vp9.webm"),
    require("./videos/Baldur's Gate 3 - Official Launch Trailer.mp4"),
    require("./videos/Dota 2 - New Hero _The Ringmaster_ Cinematic Reveal Trailer.mp4"),
    require("./videos/Last Train Home _ Release Trailer.mp4"),
    require("./videos/CIVILIZATION VI Launch Trailer.mp4"),
    require("./videos/Black Desert Online - Official Steam Launch Trailer.mp4"),
    require("./videos/World of Tanks_ Blitz - Official launch trailer.mp4"),
    require("./videos/Crusader Kings 3 - Official Story Trailer.mp4"),
    require("./videos/Hearts of Iron IV_ Arms Against Tyranny _ Official Announcement Trailer.mp4"),
    require("./videos/King Arthur_ Knight's Tale - Official Console Release Date Announcement Trailer.mp4"),
    require("./videos/Inscryption - Announce Trailer _ PS5 & PS4 Games.mp4")
];
export default videoArray;